### ISSUE TITLE
use zero-shot inference of reclip on my own images

### ISSUE THREAD

**Issue by insundaycathy** [allenai/reclip#3]
Thank you fo the great work.
I was wondering is there a way to use reclip without training on my own images?
And how would I go about doing that?
Thanks

**Comment by sanjayss34** [comment]
Hi, sorry for the delay! Yes, it's possible, and in fact, ReCLIP does not involve training steps. Please check out the code in `main.py` to see how to use ReCLIP, and let me know if you have questions about it. In particular, the workflow consists of creating an `Executor` (https://github.com/allenai/reclip/blob/main/executor.py) and running it on the image of interest, a set of bounding boxes, and a textual expression (using the `__call__` function).

**Comment by insundaycathy** [comment]
Thank for the reply, ReClip actually worked quite well on my data. But I saw that thr network uses ABERF which is pretrain on 14m data, is it possible to use CLIP instead, and is so where and I download checkpoints?

**Comment by sanjayss34** [comment]
You can specify whether to use CLIP or ALBEF via the command-line arguments. If you omit `--albef_path` from the arguments to `main.py` then CLIP will be used. You can select which CLIP model to use by specifying the model via the `--clip_model` argument.
