### ISSUE TITLE
Question about extracting region proposals in IPS module

### ISSUE THREAD

**Issue by dneirfi** [allenai/reclip#4]
Hi. 
Thank you for sharing your nice work. 

I understand the detection file (reclip_data.tar.gz) includes bounding boxes and IPS module uses these boxes for cropping and blurring. 
How did you extract the bounding boxes? using pre-trained object detector or gt boxes? 

Thanks.

**Comment by sanjayss34** [comment]
Thanks for your interest in our work.

In the files `refcoco_*.jsonl`, `refcoco+_*.jsonl`, `refcocog_*.jsonl`, and `refgta_*.jsonl`, the boxes are ground-truth boxes (where * can be replaced by train/val/test/testa/testb). We have also provided files `refcoco_dets_dict.json`, `refcoco+_dets_dict.json`, `refcocog_dets_dict.json` -- these are detected bounding boxes provided in the MAttNet repo: https://github.com/lichengunc/MAttNet (which is also used in several prior papers). For RefGTA, the files with filenames like `refgta_{val/test}_unidet{_all}_output2.json` have detected bounding boxes from UniDet: https://github.com/xingyizhou/UniDet.
